# Generated by Django 5.2 on 2025-04-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="adress",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="email@gmail.com", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="0000", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="contact",
            field=models.CharField(default="123456789", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="Jean Pierre", max_length=100),
        ),
    ]
